### ISSUE TITLE
console hard to read on light theme

### ISSUE THREAD

**Issue by skojin** [FaaStRuby/faastruby-cli#19]
It's hard to read logs in mac terminal default Novel theme

![image](https://user-images.githubusercontent.com/8044/54664646-e7541100-4af5-11e9-88f6-1bdbcf262903.png)

**Comment by parruda** [comment]
@skojin thanks for pointing that out. I will add an option to disable colors.
I wonder is there's a way to detect the terminal background color.

**Comment by skojin** [comment]
I think need to use different color, rails logs looks ok in same theme.

**Comment by parruda** [comment]
Repository moved to https://gitlab.com/faastruby/cli
